const header=document.querySelector('.site-header');const menuBtn=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>30));
menuBtn?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open))});
document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const lightbox=document.querySelector('.lightbox'),lightboxImg=lightbox.querySelector('img');document.querySelectorAll('.image-button').forEach(btn=>btn.addEventListener('click',()=>{lightboxImg.src=btn.dataset.full;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}));
function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');lightboxImg.src='';document.body.classList.remove('modal-open')}
lightbox.querySelector('.lightbox-close').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});
const booking=document.querySelector('.booking-modal'),bookingForm=document.querySelector('#bookingForm'),roomSelect=bookingForm.elements.room;
document.querySelectorAll('.open-booking').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('.room-card');if(card){const room=card.dataset.room;[...roomSelect.options].forEach((o,i)=>{if(o.textContent.startsWith(room))roomSelect.selectedIndex=i})}booking.classList.add('open');booking.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')}));
function closeBooking(){booking.classList.remove('open');booking.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')}
booking.querySelector('.booking-close').addEventListener('click',closeBooking);booking.addEventListener('click',e=>{if(e.target===booking)closeBooking()});
bookingForm.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(bookingForm);const text=`Hello, I would like to enquire about a booking.%0AName: ${encodeURIComponent(d.get('name'))}%0ARoom: ${encodeURIComponent(d.get('room'))}%0ACheck-in: ${encodeURIComponent(d.get('checkin'))}%0ACheck-out: ${encodeURIComponent(d.get('checkout'))}`;window.open(`https://wa.me/855189958899?text=${text}`,'_blank','noopener')});
let lang='zh';document.querySelectorAll('.lang-toggle').forEach(btn=>btn.addEventListener('click',()=>{lang=lang==='zh'?'en':'zh';document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.querySelectorAll('[data-zh][data-en]').forEach(el=>el.textContent=el.dataset[lang]);document.querySelectorAll('.lang-toggle').forEach(b=>b.textContent=lang==='zh'?'EN':'中')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeLightbox();closeBooking()}});
